SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE P
JOIN REST_REVIEW R ON P.MEMBER_ID = R.MEMBER_ID
WHERE P.MEMBER_NAME = (
    SELECT MEMBER_NAME
    FROM (
        SELECT P.MEMBER_NAME, COUNT(R.REVIEW_SCORE) AS SUM_REVIEW
        FROM MEMBER_PROFILE P
        JOIN REST_REVIEW R ON P.MEMBER_ID = R.MEMBER_ID
        GROUP BY P.MEMBER_NAME
        ORDER BY SUM_REVIEW DESC
        LIMIT 1
    ) AS TEMP
)
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC;
