WITH YEAR_MAX AS (
    SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE
        , YEAR(DIFFERENTIATION_DATE) AS MAX_YEAR
    FROM ECOLI_DATA 
    GROUP BY MAX_YEAR
)
SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR
    , (M.MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV
    , E.ID
FROM ECOLI_DATA AS E 
JOIN YEAR_MAX AS M 
ON YEAR(E.DIFFERENTIATION_DATE) = M.MAX_YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC
