-- 평균 일일 대여 요금 구하기
SELECT ROUND(AVG(DAILY_FEE)) AS AVERAGEE_FEE FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE = "SUV";

-- 흉부외과 또는 일반외과 의사 목록 출력하기
SELECT DR_NAME, DR_ID, MCDP_CD, DATE_FORMAT(HIRE_YMD, "%Y-%m-%d") 
  FROM DOCTOR 
  WHERE MCDP_CD = "CS" OR MCDP_CD = "GS" 
  ORDER BY HIRE_YMD DESC, DR_NAME ASC;

-- 과일로 만든 아이스크림 고르기
SELECT FLAVOR FROM ICECREAM_INFO
WHERE INGREDIENT_TYPE = "fruit_based"
AND FLAVOR IN (SELECT FLAVOR FROM FIRST_HALF
              WHERE TOTAL_ORDER > 3000)
              ORDER BY FLAVOR ASC;

-- 3월에 태어난 여성 회원 목록 출력하기
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, "%Y-%m-%d") AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE SUBSTRING(DATE_OF_BIRTH, 6, 2) = '03'
AND GENDER = 'W'
AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC;

-- 역순 정렬하기
SELECT NAME, DATETIME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID DESC;

-- 재구매가 일어난 상품과 회원 리스트 구하기
SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(*) > 1
ORDER BY USER_ID ASC, PRODUCT_ID DESC;
